name = "hugo-theme-console"
license = "MIT"
licenselink = "https://github.com/zemzale/hugo-theme-console/blob/master/LICENSE"
description = "A minimal, dark, responsive and light theme for Hugo inspired by Linux console."
homepage = "https://github.com/zemzale/hugo-theme-console"
tags = ["blog", "gallery", "portfolio", "console", "terminal", "clean", "personal", "minimal", "monotone", "simple", "technical", "responsive", "mobile", "minimalist", "retro", "animation"]
features = ["disqus", "responsive", "google analytics"]
min_version = "0.69.0"

[author]
    name = "Alberts Zemzale"
    homepage = "https://zemzale.com"
    github = "https://github.com/zemzale"

[original]
    name = "Marcin Mierzejewski"
    homepage = "https://mrmierzejewski.com"
    github = "https://github.com/mrmierzejewski"
